-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 15:42:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`images` ;

CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id` INT NOT NULL,
  `image_name` VARCHAR(45) NULL,
  `image_desc` VARCHAR(90) NULL,
  `image_url` VARCHAR(150) NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(40) NOT NULL,
  `profile_icon_url` INT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `profile_icon_idx` (`profile_icon_url` ASC) VISIBLE,
  CONSTRAINT `profile_icon`
    FOREIGN KEY (`profile_icon_url`)
    REFERENCES `mydb`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publisher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publisher` (
  `publisher_id` INT NOT NULL,
  `publisher_name` VARCHAR(45) NULL,
  `publisher_desc` VARCHAR(1000) NULL,
  `publisher_icon_url` INT NULL,
  PRIMARY KEY (`publisher_id`),
  INDEX `publisher_icon_idx` (`publisher_icon_url` ASC) VISIBLE,
  CONSTRAINT `publisher_icon`
    FOREIGN KEY (`publisher_icon_url`)
    REFERENCES `mydb`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hardware`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hardware` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hardware` (
  `hardware_id` INT NOT NULL,
  `cpu` VARCHAR(45) NULL,
  `memory` VARCHAR(45) NULL,
  `storage` VARCHAR(45) NULL,
  `graphics` VARCHAR(45) NULL,
  PRIMARY KEY (`hardware_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_hardware`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`game_hardware` ;

CREATE TABLE IF NOT EXISTS `mydb`.`game_hardware` (
  `game_id` INT NOT NULL,
  `windows` TINYINT NULL,
  `linux` TINYINT NULL,
  `mac` TINYINT NULL,
  `windows_min_spec` INT NULL,
  `linux_min_spec` INT NULL,
  `mac_min_spec` INT NULL,
  `windows_rec_spec` INT NULL,
  `linux_rec_spec` INT NULL,
  `mac_rec_spec` INT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `windows_min_spec_idx` (`windows_min_spec` ASC) VISIBLE,
  INDEX `windows_rec_spec_idx` (`windows_rec_spec` ASC) VISIBLE,
  INDEX `linux_min_spec_idx` (`linux_min_spec` ASC) VISIBLE,
  INDEX `linux_rec_spec_idx` (`linux_rec_spec` ASC) VISIBLE,
  INDEX `mac_min_spec_idx` (`mac_min_spec` ASC) VISIBLE,
  INDEX `mac_rec_spec_idx` (`mac_rec_spec` ASC) VISIBLE,
  CONSTRAINT `windows_min_spec`
    FOREIGN KEY (`windows_min_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `windows_rec_spec`
    FOREIGN KEY (`windows_rec_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linux_min_spec`
    FOREIGN KEY (`linux_min_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `linux_rec_spec`
    FOREIGN KEY (`linux_rec_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mac_min_spec`
    FOREIGN KEY (`mac_min_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mac_rec_spec`
    FOREIGN KEY (`mac_rec_spec`)
    REFERENCES `mydb`.`hardware` (`hardware_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`game_titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`game_titles` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NOT NULL,
  `desc` VARCHAR(2000) NULL,
  `publisher_id` INT NOT NULL,
  `multiplayer` TINYINT NOT NULL,
  `hardware_req` INT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `hardware_req_idx` (`hardware_req` ASC) VISIBLE,
  CONSTRAINT `publisher_id`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `mydb`.`publisher` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hardware_req`
    FOREIGN KEY (`hardware_req`)
    REFERENCES `mydb`.`game_hardware` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activated_titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activated_titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activated_titles` (
  `account_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `game_id_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game_titles` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`friends` ;

CREATE TABLE IF NOT EXISTS `mydb`.`friends` (
  `account_1` INT NOT NULL,
  `account_2` INT NOT NULL,
  INDEX `account_1_idx` (`account_1` ASC, `account_2` ASC) VISIBLE,
  INDEX `account_2_idx` (`account_2` ASC, `account_1` ASC) VISIBLE,
  CONSTRAINT `account_1`
    FOREIGN KEY (`account_1`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_2`
    FOREIGN KEY (`account_2`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bans` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bans` (
  `account_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `reason` VARCHAR(200) NULL,
  `expires` DATETIME NULL,
  PRIMARY KEY (`account_id`),
  INDEX `game_id_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game_titles` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reviews` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reviews` (
  `review_id` INT NOT NULL,
  `game_id` INT NULL,
  `review_text` VARCHAR(1000) NULL,
  `review_score` INT NULL,
  `reviewer_id` INT NULL,
  PRIMARY KEY (`review_id`),
  CONSTRAINT `game_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`game_titles` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`account` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review_rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review_rating` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `review_id` INT NULL,
  `review_is_helpful` TINYINT NULL,
  `rating_by` INT NULL,
  PRIMARY KEY (`rating_id`),
  UNIQUE INDEX `rating_id_UNIQUE` (`rating_id` ASC) VISIBLE,
  INDEX `rating_by_idx` (`rating_by` ASC) VISIBLE,
  INDEX `review_id_idx` (`review_id` ASC) VISIBLE,
  CONSTRAINT `rating_by`
    FOREIGN KEY (`rating_by`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `review_id`
    FOREIGN KEY (`review_id`)
    REFERENCES `mydb`.`reviews` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `chat_id` INT NOT NULL,
  `chat_name` VARCHAR(45) NULL,
  `chat_img` INT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `chat_img_idx` (`chat_img` ASC) VISIBLE,
  CONSTRAINT `chat_img`
    FOREIGN KEY (`chat_img`)
    REFERENCES `mydb`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `message_id` INT NOT NULL,
  `sender_id` INT NULL,
  `message_text` VARCHAR(200) NULL,
  `chat_id` INT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `sender_id_idx` (`sender_id` ASC) VISIBLE,
  INDEX `chat_id_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `sender_id`
    FOREIGN KEY (`sender_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `mydb`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_in_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_in_chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_in_chat` (
  `chat_id` INT NOT NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `mydb`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
