-- MySQL Script generated by MySQL Workbench
-- Wed Mar 19 15:22:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marketplace` DEFAULT CHARACTER SET utf8 ;
USE `marketplace` ;

-- -----------------------------------------------------
-- Table `marketplace`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`account` (
  `account_id` INT NOT NULL,
  `email` VARCHAR(320) NULL,
  `username` VARCHAR(45) NULL,
  `password_hash` CHAR(64) NULL,
  `profile_pic_url` VARCHAR(200) NULL,
  `account_banned` TINYINT NULL,
  `account_created` DATETIME NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`publisher` (
  `publisher_id` INT NOT NULL,
  `publisher_name` VARCHAR(50) NULL,
  `bio` VARCHAR(500) NULL,
  `publisher_admin` INT NULL,
  PRIMARY KEY (`publisher_id`),
  UNIQUE INDEX `publisher_id_UNIQUE` (`publisher_id` ASC) VISIBLE,
  INDEX `publisher_admin_idx` (`publisher_admin` ASC) VISIBLE,
  CONSTRAINT `publisher_admin`
    FOREIGN KEY (`publisher_admin`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`system_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`system_requirements` (
  `requirements_id` INT NOT NULL,
  `mac` TINYINT NULL,
  `windows` TINYINT NULL,
  `linux` TINYINT NULL,
  `min_cpu` VARCHAR(50) NULL,
  `min_memory` VARCHAR(8) NULL,
  `min_gpu` VARCHAR(50) NULL,
  `storage` VARCHAR(8) NULL,
  PRIMARY KEY (`requirements_id`),
  UNIQUE INDEX `requirements_id_UNIQUE` (`requirements_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`game` (
  `game_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `desc` VARCHAR(200) NULL,
  `multiplayer` TINYINT NULL,
  `publisher` INT NULL,
  `release_date` DATETIME NULL,
  `system_requirements` INT NULL,
  `price` DECIMAL(2) NULL,
  PRIMARY KEY (`game_id`),
  UNIQUE INDEX `game_id_UNIQUE` (`game_id` ASC) VISIBLE,
  INDEX `publisher_idx` (`publisher` ASC) VISIBLE,
  INDEX `system_requirements_idx` (`system_requirements` ASC) VISIBLE,
  CONSTRAINT `game_publisher`
    FOREIGN KEY (`publisher`)
    REFERENCES `marketplace`.`publisher` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `system_requirements`
    FOREIGN KEY (`system_requirements`)
    REFERENCES `marketplace`.`system_requirements` (`requirements_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`review` (
  `review_id` INT NOT NULL,
  `written_by` INT NULL,
  `game` INT NULL,
  `review_text` VARCHAR(500) NULL,
  `rating` INT NULL,
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `review_id_UNIQUE` (`review_id` ASC) VISIBLE,
  INDEX `written_by_idx` (`written_by` ASC) VISIBLE,
  INDEX `game_idx` (`game` ASC) VISIBLE,
  CONSTRAINT `written_by`
    FOREIGN KEY (`written_by`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `review_game`
    FOREIGN KEY (`game`)
    REFERENCES `marketplace`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`genre` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(20) NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `genre_id_UNIQUE` (`genre_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`game_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`game_genres` (
  `game` INT NOT NULL,
  `genre` INT NOT NULL,
  PRIMARY KEY (`game`, `genre`),
  INDEX `genre_idx` (`genre` ASC) VISIBLE,
  CONSTRAINT `game_genre_game`
    FOREIGN KEY (`game`)
    REFERENCES `marketplace`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game_genre_genre`
    FOREIGN KEY (`genre`)
    REFERENCES `marketplace`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`game_ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`game_ban` (
  `ban_id` INT NOT NULL,
  `account` INT NULL,
  `game` INT NULL,
  `reason` VARCHAR(50) NULL,
  `expires` DATETIME NULL,
  `started` DATETIME NULL,
  PRIMARY KEY (`ban_id`),
  UNIQUE INDEX `ban_id_UNIQUE` (`ban_id` ASC) VISIBLE,
  INDEX `account_idx` (`account` ASC) VISIBLE,
  INDEX `game_idx` (`game` ASC) VISIBLE,
  CONSTRAINT `ban_account`
    FOREIGN KEY (`account`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ban_game`
    FOREIGN KEY (`game`)
    REFERENCES `marketplace`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`account_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`account_games` (
  `account` INT NOT NULL,
  `game` INT NOT NULL,
  PRIMARY KEY (`account`, `game`),
  INDEX `game_idx` (`game` ASC) VISIBLE,
  CONSTRAINT `account`
    FOREIGN KEY (`account`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `game`
    FOREIGN KEY (`game`)
    REFERENCES `marketplace`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`chat` (
  `chat_id` INT NOT NULL,
  `chat_name` VARCHAR(30) NULL,
  `chat_image_url` VARCHAR(200) NULL,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`user_in_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`user_in_chat` (
  `chat_id` INT NOT NULL,
  `account` INT NOT NULL,
  PRIMARY KEY (`chat_id`, `account`),
  INDEX `account_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `marketplace`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account`
    FOREIGN KEY (`account`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`message` (
  `message_id` INT NOT NULL,
  `sent_by` INT NULL,
  `chat_id` INT NULL,
  `text` VARCHAR(200) NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`message_id`),
  INDEX `sent_by_idx` (`sent_by` ASC) VISIBLE,
  INDEX `chat_id_idx` (`chat_id` ASC) VISIBLE,
  CONSTRAINT `sent_by`
    FOREIGN KEY (`sent_by`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `marketplace`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`friends` (
  `account1` INT NOT NULL,
  `account2` INT NOT NULL,
  `friends_since` DATETIME NULL,
  PRIMARY KEY (`account1`, `account2`),
  INDEX `account2_idx` (`account2` ASC) VISIBLE,
  CONSTRAINT `account1`
    FOREIGN KEY (`account1`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account2`
    FOREIGN KEY (`account2`)
    REFERENCES `marketplace`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
