-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 16:11:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testDB` DEFAULT CHARACTER SET utf8 ;
USE `testDB` ;

-- -----------------------------------------------------
-- Table `testDB`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testDB`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `email` VARCHAR(200) NULL,
  `dob` DATE NULL,
  `startDate` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testDB`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testDB`.`student` (
  `studentID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `endDate` DATE NULL,
  `course` VARCHAR(45) NULL,
  `personID` INT NULL,
  PRIMARY KEY (`studentID`),
  INDEX `personID_idx` (`personID` ASC) VISIBLE,
  CONSTRAINT `personID`
    FOREIGN KEY (`personID`)
    REFERENCES `testDB`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testDB`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testDB`.`staff` (
  `staffID` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(75) NULL,
  `manager` INT NULL,
  `person` INT NULL,
  PRIMARY KEY (`staffID`),
  UNIQUE INDEX `staffID_UNIQUE` (`staffID` ASC) VISIBLE,
  INDEX `personID_idx` (`person` ASC) VISIBLE,
  CONSTRAINT `personID`
    FOREIGN KEY (`person`)
    REFERENCES `testDB`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
