-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 16:07:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lesson5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lesson5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lesson5` DEFAULT CHARACTER SET utf8 ;
USE `lesson5` ;

-- -----------------------------------------------------
-- Table `lesson5`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lesson5`.`building` ;

CREATE TABLE IF NOT EXISTS `lesson5`.`building` (
  `name` VARCHAR(100) NOT NULL,
  `campus` VARCHAR(100) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lesson5`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lesson5`.`room` ;

CREATE TABLE IF NOT EXISTS `lesson5`.`room` (
  `building_name` VARCHAR(100) NOT NULL,
  `floor` INT NULL,
  `capacity` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `name`
    FOREIGN KEY (`building_name`)
    REFERENCES `lesson5`.`building` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lesson5`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lesson5`.`module` ;

CREATE TABLE IF NOT EXISTS `lesson5`.`module` (
  `name` VARCHAR(45) NOT NULL,
  `school` VARCHAR(100) NULL,
  `lecturer` VARCHAR(50) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lesson5`.`lesson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lesson5`.`lesson` ;

CREATE TABLE IF NOT EXISTS `lesson5`.`lesson` (
  `number` INT NOT NULL,
  `topic` VARCHAR(45) NULL,
  `room` VARCHAR(45) NULL,
  PRIMARY KEY (`number`),
  INDEX `name_idx` (`room` ASC) VISIBLE,
  INDEX `topic_idx` (`topic` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`room`)
    REFERENCES `lesson5`.`room` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topic`
    FOREIGN KEY (`topic`)
    REFERENCES `lesson5`.`module` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
