USE marketplace;

-- Delete friend
DELETE FROM friends
WHERE (account1 = LEAST(1, 3) AND account2 = GREATEST(1, 3));

-- Delete an account
-- email hash would be generated by server in reality
CALL SoftAccountDelete(2, 'example_email_hash');

-- Delete account fully after retention period
CALL FullAccountDelete(2);

-- Delete a review that has an offensive message (example condition)
DELETE FROM review
WHERE review_text LIKE '%offensive%';